-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE,
       SUM(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) as SALES
       FROM PRODUCT 
       join OFFLINE_SALE
       on PRODUCT.PRODUCT_ID	= OFFLINE_SALE.PRODUCT_ID
       GROUP BY OFFLINE_SALE.PRODUCT_ID
       ORDER BY SALES DESC,PRODUCT_CODE ASC;