SELECT 
    a.BOOK_ID AS BOOK_ID,
    b.AUTHOR_NAME AS AUTHOR_NAME,
    DATE_FORMAT(a.PUBLISHED_DATE,"%Y-%m-%d") AS PUBLISHED_DATE
    FROM BOOK a
    left Join AUTHOR b ON a.AUTHOR_ID = b.AUTHOR_ID
    WHERE a.CATEGORY = '경제'
    ORDER BY a.PUBLISHED_DATE ASC;